# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "SourceScout"
client_id = "4c363438ac4797bd0a851690797b6fd2"
application_url = "https://partially-open-orca.ngrok-free.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://partially-open-orca.ngrok-free.app/auth/callback",
  "http://localhost:3001/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sourcescout.myshopify.com"
